defaults:
  - trainset_corruption: null #can be overriden!
  - valset_corruption: null #can be overriden!
  - testset_corruption: null #can be overriden!

_target_: src.datamodules.datamodules.AmbiMNISTDataModule
data_dir: '/home/elpis_ubuntu/data/'
batch_size: 320
num_workers: 4
pin_memory: True
shuffle: True
trainset_data_aug: False
valset_data_aug: False
